FROM python:3.10-slim

# Install tesseract system dependencies
RUN apt-get update && apt-get install -y \
    tesseract-ocr libglib2.0-0 libsm6 libxext6 libxrender-dev && apt-get clean

WORKDIR /app

# 👉 Copy only requirements.txt first
COPY requirements.txt .

# ✅ Install dependencies (this layer gets cached)
RUN pip install --no-cache-dir --no-deps torch && \
    pip install --no-cache-dir -r requirements.txt



# 👉 Now copy your source code
COPY . .

ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata

EXPOSE 5000

CMD ["python", "app.py"]
