# Base image with Python
FROM python:3.10-slim

# Install dependencies for tesseract
RUN apt-get update && \
    apt-get install -y tesseract-ocr libglib2.0-0 libsm6 libxext6 libxrender-dev && \
    apt-get clean

# Set working directory
WORKDIR /app

# Copy code and install Python packages
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable for Tesseract
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata

# Expose port
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
